In [3]:
import numpy as np

In [7]:
#Q1
#(a)
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

Reversed array: [5 4 6 3 2 1]


In [9]:
#(b)
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Method 1: .flatten()
flat1 = array1.flatten()


flat2 = array1.ravel()

print("Flatten using flatten():", flat1)
print("Flatten using ravel():", flat2)

Flatten using flatten(): [1 2 3 2 4 5 1 2 3]
Flatten using ravel(): [1 2 3 2 4 5 1 2 3]


In [49]:
# (c) Compare arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison = (arr1== arr2) 
print(comparison)

[[ True  True]
 [ True  True]]


In [51]:
# (d) Find most frequent value and indices
# i.
x = np.array([1,2,3,4,5,1,2,1,1,1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]
print(f"Most frequent value in x: {most_frequent}")
print(f"Indices: {indices}")

# ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print(f"Most frequent value in y: {most_frequent}")
print(f"Indices: {indices}")


Most frequent value in x: 1
Indices: [0 5 7 8 9]
Most frequent value in y: 1
Indices: [0 1 2]


In [53]:
# (e) Matrix operations
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all = np.sum(gfg)
sum_row = np.sum(gfg, axis=1)
sum_col = np.sum(gfg, axis=0)
print("Sum of all elements:", sum_all)
print("Row-wise sum:", sum_row.flatten())
print("Column-wise sum:", sum_col) 

Sum of all elements: 45
Row-wise sum: [[14 16 15]]
Column-wise sum: [[20  9 16]]


In [61]:
# (f) Matrix properties
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
diag_sum = np.trace(n_array)
print("Sum of diagonal elements:", diag_sum)
eigenvals, eigenvecs = np.linalg.eig(n_array)
print("Eigenvalues:", eigenvals)
print("Eigenvectors:\n", eigenvecs)
inv_matrix = np.linalg.inv(n_array)
print("Inverse:\n", inv_matrix)
det = np.linalg.det(n_array)
print("Determinant:", det)



Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [55]:
# (g) Matrix multiplication and covariance
# i.
p = np.array([[1, 2],
              [2, 3]])
q = np.array([[4, 5],
              [6, 7]])
mult = np.dot(p, q)
print("Matrix multiplication (p @ q):\n", mult)

cov = np.cov(p, q, rowvar=False) 
pq = np.column_stack((p.flatten(), q.flatten()))
cov_pq = np.cov(pq.T)
print("Covariance between flattened p and q:\n", cov_pq)
#ii
p = np.array([[1, 2],
              [2, 3],
              [4, 5]])

q = np.array([[4, 5, 1],
              [6, 7, 2]])  

mult = np.dot(p, q)
print("Matrix multiplication (p @ q):\n", mult)

p_flat = p.flatten()  
q_flat = q.flatten()  
cov = np.cov(p_flat, q_flat)
print("Covariance between p and q (flattened):\n", cov)



Matrix multiplication (p @ q):
 [[16 19]
 [26 31]]
Covariance between flattened p and q:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Matrix multiplication (p @ q):
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between p and q (flattened):
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [57]:
# (h) Vector products
x_arr = np.array([[2, 3, 4], [3, 2, 9]])
y_arr = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x_arr, y_arr)
outer = np.outer(x_arr, y_arr)
cartesian = np.array(np.meshgrid(x_arr.flatten(), y_arr.flatten())).T.reshape(-1, 2)
print("Inner product (row-wise):\n", inner)
print("Outer product (flattened):\n", outer.shape) 
print("Cartesian product shape:", cartesian.shape)


Inner product (row-wise):
 [[17 52]
 [13 62]]
Outer product (flattened):
 (6, 6)
Cartesian product shape: (36, 2)


In [67]:
# Q2: Mathematics and Statistics
# (a)
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)

flat = array.flatten()
percentiles_flat = np.percentile(flat, [25, 50, 75])
percentiles_col = np.percentile(array, [25, 50, 75], axis=0)
percentiles_row = np.percentile(array, [25, 50, 75], axis=1)

mean_flat, median_flat, std_flat = np.mean(flat), np.median(flat), np.std(flat)
mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print("Mean per column:", mean_col)
print("Median per column:", median_col)
print("Std per column:",std_col)
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print("Mean per row:", mean_row)
print("Median per row:", median_row)
print("Std per row:", std_row)


Mean per column: [-1.5  1.5 -1.5]
Median per column: [-1.5  1.5 -1.5]
Std per column: [2.5 3.5 4.5]
Mean per row: [ 0.66666667 -1.66666667]
Median per row: [ 1. -4.]
Std per row: [2.05480467 4.78423336]


In [69]:
# (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor_a = np.floor(a)
ceil_a = np.ceil(a)
trunc_a = np.trunc(a)
round_a = np.round(a)
print("Original:", a)
print("Floor:", floor_a)
print("Ceil:", ceil_a)
print("Truncate:", trunc_a)
print("Rounded:", round_a)

Original: [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Truncate: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [73]:
# Q3: Searching and Sorting
# (a)
array_a = np.array([10, 52, 62, 16, 16, 54, 453])
# i. 
sorted_arr = np.sort(array_a)
print("Sorted array:", sorted_arr)
# ii. 
sorted_indices = np.argsort(array_a)
print("Indices of sorted array:", sorted_indices)
# iii. 
smallest_4 = np.partition(array_a, 4)[:4]
print("4 smallest:", smallest_4)
# iv.
largest_5 = np.partition(array_a, -5)[-5:]
print("5 largest (via argpartition):", np.sort(largest_5))


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest: [16 10 16 52]
5 largest (via argpartition): [ 16  52  54  62 453]


In [71]:
# (b)
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
# i.
int_elements = array_b[array_b == array_b.astype(int)]
print("Integer elements:", int_elements)
# ii. 
float_elements = array_b[array_b != array_b.astype(int)]
print("Non-integer float elements:", float_elements)

Integer elements: [1. 2. 3. 2.]
Non-integer float elements: [1.2 2.2]
